[build]
  base = "app-tfg"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "CLOUDINARY_PROFILE_IMAGES_FOLDER,GEOCODING_PROVIDER,GEOCODING_COUNTRY_NAME,GEOCODING_USER_AGENT,GEOCODING_BASE_URL,AUTH_URL,NEXTAUTH_URL,APP_BASE_URL,NEXT_PUBLIC_APP_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
